### ISSUE TITLE
Add MDL

### ISSUE THREAD

**Issue by arthurvr** [sachin1092/awesome-material#4]
https://github.com/google/material-design-lite/

**Comment by sachin1092** [comment]
Please create a pull request.

**Comment by arthurvr** [comment]
The fact that I didn't create a pull request can't be a reason to close the issue. It's something that would improve the list so if somebody created a PR or not shouldn't matter.

**Comment by sachin1092** [comment]
Okay, no issues bro.
I ll add the libraries. :)

**Comment by sachin1092** [comment]
Added MDL.
